#ifndef CONTENT_GENERATED_H
#define CONTENT_GENERATED_H

// Auto-generated from a-e-w-mason_the-four-feathers.epub. Do not edit manually.
static const char chapter_title[] =
    "The Four Feathers";

static const char chapter_content[] =
    "I\n\nA Crimean Night\n\nLieutenant Sutch was the first of General Feversham\342\200\231s guests "
    "to reach Broad Place. He arrived about five o\342\200\231clock on an afternoon of sunshine in mi"
    "d June, and the old redbrick house, lodged on a southern slope of the Surrey hills, was glowing "
    "from a dark forest depth of pines with the warmth of a rare jewel. Lieutenant Sutch limped acros"
    "s the hall, where the portraits of the Fevershams rose one above the other to the ceiling, and w"
    "ent out on to the stone-flagged terrace at the back. There he found his host sitting erect like "
    "a boy, and gazing southward toward the Sussex Downs.\n\n\342\200\234How\342\200\231s the leg?"
    "\342\200\235 asked General Feversham, as he rose briskly from his chair. He was a small wiry man"
    ", and, in spite of his white hairs, alert. But the alertness was of the body. A bony face, with "
    "a high narrow forehead and steel-blue inexpressive eyes, suggested a barrenness of mind.\n\n\342"
    "\200\234It gave me trouble during the winter,\342\200\235 replied Sutch. \342\200\234But that wa"
    "s to be expected.\342\200\235 General Feversham nodded, and for a little while both men were sil"
    "ent. From the terrace the ground fell steeply to a wide level plain of brown earth and emerald f"
    "ields and dark clumps of trees. From this plain voices rose through the sunshine, small but very"
    " clear. Far away toward Horsham a coil of white smoke from a train snaked rapidly in and out amo"
    "ngst the trees; and on the horizon rose the Downs, patched with white chalk.\n\n\342\200\234I th"
    "ought that I should find you here,\342\200\235 said Sutch.\n\n\342\200\234It was my wife\342\200"
    "\231s favourite corner,\342\200\235 answered Feversham in a quite emotionless voice. \342\200"
    "\234She would sit here by the hour. She had a queer liking for wide and empty spaces.\342\200"
    "\235\n\n\342\200\234Yes,\342\200\235 said Sutch. \342\200\234She had imagination. Her thoughts c"
    "ould people them.\342\200\235\n\nGeneral Feversham glanced at his companion as though he hardly "
    "understood. But he asked no questions. What he did not understand he habitually let slip from hi"
    "s mind as not worth comprehension. He spoke at once upon a different topic.\n\n\342\200\234There"
    " will be a leaf out of our table tonight.\342\200\235\n\n\342\200\234Yes. Collins, Barberton, an"
    "d Vaughan went this winter. Well, we are all permanently shelved upon the world\342\200\231s hal"
    "f-pay list as it is. The obituary column is just the last formality which gazettes us out of the"
    " service altogether,\342\200\235 and Sutch stretched out and eased his crippled leg, which fourt"
    "een years ago that day had been crushed and twisted in the fall of a scaling-ladder.\n\n\342\200"
    "\234I am glad that you came before the others,\342\200\235 continued Feversham. \342\200\234I wo"
    "uld like to take your opinion. This day is more to me than the anniversary of our attack upon th"
    "e Redan. At the very moment when we were standing under arms in the dark\342\200\224\342\200\235"
    "\n\n\342\200\234To the west of the quarries; I remember,\342\200\235 interrupted Sutch, with a d"
    "eep breath. \342\200\234How should one forget?\342\200\235\n\n\342\200\234At that very moment Ha"
    "rry was born in this house. I thought, therefore, that if you did not object, he might join us t"
    "onight. He happens to be at home. He will, of course, enter the service, and he might learn some"
    "thing, perhaps, which afterward will be of use\342\200\224one never knows.\342\200\235\n\n\342"
    "\200\234By all means,\342\200\235 said Sutch, with alacrity. For since his visits to General Fev"
    "ersham were limited to the occasion of these anniversary dinners, he had never yet seen Harry Fe"
    "versham.\n\nSutch had for many years been puzzled as to the qualities in General Feversham which"
    " had attracted Muriel Graham, a woman as remarkable for the refinement of her intellect as for t"
    "he beauty of her person; and he could never find an explanation. He had to be content with his k"
    "nowledge that for some mysterious reason she had married this man so much older than herself, an"
    "d so unlike to her in character. Personal courage and an indomitable self-confidence were the ch"
    "ief, indeed the only, qualities which sprang to light in General Feversham. Lieutenant Sutch wen"
    "t back in thought over twenty years, as he sat on his garden-chair, to a time before he had take"
    "n part, as an officer of the Naval Brigade, in that unsuccessful onslaught on the Redan. He reme"
    "mbered a season in London to which he had come fresh from the China station; and he was curious "
    "to see Harry Feversham. He did not admit that it was more than the natural curiosity of a man wh"
    "o, disabled in comparative youth, had made a hobby out of the study of human nature. He was inte"
    "rested to see whether the lad took after his mother or his father\342\200\224that was all.\n\nSo"
    " that night Harry Feversham took a place at the dinner-table and listened to the stories which h"
    "is elders told, while Lieutenant Sutch watched him. The stories were all of that dark winter in "
    "the Crimea, and a fresh story was always in the telling before its predecessor was ended. They w"
    "ere stories of death, of hazardous exploits, of the pinch of famine, and the chill of snow. But "
    "they were told in clipped words and with a matter-of-fact tone, as though the men who related th"
    "em were only conscious of them as far-off things; and there was seldom a comment more pronounced"
    " than a mere \342\200\234that\342\200\231s curious,\342\200\235 or an exclamation more significa"
    "nt than a laugh.\n\nBut Harry Feversham sat listening as though the incidents thus carelessly na"
    "rrated were happening actually at that moment and within the walls of that room. His dark eyes"
    "\342\200\224the eyes of his mother\342\200\224turned with each story from speaker to speaker, an"
    "d waited, wide open and fixed, until the last word was spoken. He listened fascinated and enthra"
    "lled. And so vividly did the changes of expression shoot and quiver across his face, that it see"
    "med to Sutch the lad must actually hear the drone of bullets in the air, actually resist the stu"
    "nning shock of a charge, actually ride down in the thick of a squadron to where guns screeched o"
    "ut a tongue of flame from a fog. Once a major of artillery spoke of the suspense of the hours be"
    "tween the parading of the troops before a battle and the first command to advance; and Harry\342"
    "\200\231s shoulders worked under the intolerable strain of those lagging minutes.\n\nBut he did "
    "more than work his shoulders. He threw a single furtive, wavering glance backwards; and Lieutena"
    "nt Sutch was startled, and indeed more than startled\342\200\224he was pained. For this after al"
    "l was Muriel Graham\342\200\231s boy.\n\nThe look was too familiar a one to Sutch. He had seen i"
    "t on the faces of recruits during their first experience of a battle too often for him to misund"
    "erstand it. And one picture in particular rose before his mind. An advancing square at Inkermann"
    ", and a tall big soldier rushing forward from the line in the eagerness of his attack, and then "
    "stopping suddenly as though he suddenly understood that he was alone, and had to meet alone the "
    "charge of a mounted Cossack. Sutch remembered very clearly the fatal wavering glance which the b"
    "ig soldier had thrown backward toward his companions\342\200\224a glance accompanied by a queer "
    "sickly smile. He remembered too, with equal vividness, its consequence. For though the soldier c"
    "arried a loaded musket and a bayonet locked to the muzzle, he had without an effort of self-defe"
    "nce received the Cossack\342\200\231s lance-thrust in his throat.\n\nSutch glanced hurriedly abo"
    "ut the table, afraid that General Feversham, or that some one of his guests, should have remarke"
    "d the same look and the same smile upon Harry\342\200\231s face. But no one had eyes for the lad"
    "; each visitor was waiting too eagerly for an opportunity to tell a story of his own. Sutch drew"
    " a breath of relief and turned to Harry. But the boy was sitting with his elbows on the cloth an"
    "d his head propped between his hands, lost to the glare of the room and its glitter of silver, c"
    "onstructing again out of the swift succession of anecdotes a world of cries and wounds, and madd"
    "ened riderless chargers and men writhing in a fog of cannon-smoke. The curtest, least graphic de"
    "scription of the biting days and nights in the trenches set the lad shivering. Even his face gre"
    "w pinched, as though the iron frost of that winter was actually eating into his bones. Sutch tou"
    "ched him lightly on the elbow.\n\n\342\200\234You renew those days for me,\342\200\235 said he. "
    "\342\200\234Though the heat is dripping down the windows, I feel the chill of the Crimea.\342"
    "\200\235\n\nHarry roused himself from his absorption.\n\n\342\200\234The stories renew them,\342"
    "\200\235 said he.\n\n\342\200\234No. It is you listening to the stories.\342\200\235\n\nAnd befo"
    "re Harry could reply, General Feversham\342\200\231s voice broke sharply in from the head of the"
    " table:\342\200\224\n\n\342\200\234Harry, look at the clock!\342\200\235\n\nAt once all eyes wer"
    "e turned upon the lad. The hands of the clock made the acutest of angles. It was close upon midn"
    "ight; and from eight, without so much as a word or a question, he had sat at the dinner-table li"
    "stening. Yet even now he rose with reluctance.\n\n\342\200\234Must I go, father?\342\200\235 he "
    "asked, and the general\342\200\231s guests intervened in a chorus. The conversation was clear ga"
    "in to the lad, a first taste of powder which might stand him in good stead afterwards.\n\n\342"
    "\200\234Besides, it\342\200\231s the boy\342\200\231s birthday,\342\200\235 added the major of a"
    "rtillery. \342\200\234He wants to stay; that\342\200\231s plain. You wouldn\342\200\231t find a "
    "youngster of fourteen sit all these hours without a kick of the foot against the table-leg unles"
    "s the conversation entertained him. Let him stay, Feversham!\342\200\235\n\nFor once General Fev"
    "ersham relaxed the iron discipline under which the boy lived.\n\n\342\200\234Very well,\342\200"
    "\235 said he. \342\200\234Harry shall have an hour\342\200\231s furlough from his bed. A single "
    "hour won\342\200\231t make much difference.\342\200\235\n\nHarry\342\200\231s eyes turned toward"
    " his father, and just for a moment rested upon his face with a curious steady gaze. It seemed to"
    " Sutch that they uttered a question, and, rightly or wrongly, he interpreted the question into w"
    "ords:\342\200\224\n\n\342\200\234Are you blind?\342\200\235\n\nBut General Feversham was already"
    " talking to his neighbours, and Harry quietly sat down, and again propping his chin upon his han"
    "ds, listened with all his soul. Yet he was not entertained; rather he was enthralled; he sat qui"
    "et under the compulsion of a spell. His face became unnaturally white, his eyes unnaturally larg"
    "e, while the flames of the candles shone ever redder and more blurred through a blue haze of tob"
    "acco smoke, and the level of the wine grew steadily lower in the decanters.\n\nThus half of that"
    " one hour\342\200\231s furlough was passed; and then General Feversham, himself jogged by the un"
    "lucky mention of a name, suddenly blurted out in his jerky fashion:\342\200\224\n\n\342\200\234L"
    "ord Wilmington. One of the best names in England, if you please. Did you ever see his house in W"
    "arwickshire? Every inch of the ground you would think would have a voice to bid him play the man"
    ", if only in remembrance of his fathers. \342\200\246 It seemed incredible and mere camp rumour,"
    " but the rumour grew. If it was whispered at the Alma, it was spoken aloud at Inkermann, it was "
    "shouted at Balaclava. Before Sebastopol the hideous thing was proved. Wilmington was acting as g"
    "alloper to his general. I believe upon my soul the general chose him for the duty, so that the f"
    "ellow might set himself right. There were three hundred yards of bullet-swept flat ground, and a"
    " message to be carried across them. Had Wilmington toppled off his horse on the way, why, there "
    "were the whispers silenced forever. Had he ridden through alive he earned distinction besides. B"
    "ut he didn\342\200\231t dare; he refused! Imagine it if you can! He sat shaking on his horse and"
    " declined. You should have seen the general. His face turned the colour of that Burgundy. \342"
    "\200\230No doubt you have a previous engagement,\342\200\231 he said, in the politest voice you "
    "ever heard\342\200\224just that, not a word of abuse. A previous engagement on the battlefield! "
    "For the life of me, I could hardly help laughing. But it was a tragic business for Wilmington. H"
    "e was broken, of course, and slunk back to London. Every house was closed to him; he dropped out"
    " of his circle like a lead bullet you let slip out of your hand into the sea. The very women in "
    "Piccadilly spat if he spoke to them; and he blew his brains out in a back bedroom off the Haymar"
    "ket. Curious that, eh? He hadn\342\200\231t the pluck to face the bullets when his name was at s"
    "take, yet he could blow his own brains out afterwards.\342\200\235\n\nLieutenant Sutch chanced t"
    "o look at the clock as the story came to an end. It was now a quarter to one. Harry Feversham ha"
    "d still a quarter of an hour\342\200\231s furlough, and that quarter of an hour was occupied by "
    "a retired surgeon-general with a great wagging beard, who sat nearly opposite to the boy.\n\n"
    "\342\200\234I can tell you an incident still more curious,\342\200\235 he said. \342\200\234The "
    "man in this case had never been under fire before, but he was of my own profession. Life and dea"
    "th were part of his business. Nor was he really in any particular danger. The affair happened du"
    "ring a hill campaign in India. We were encamped in a valley, and a few Pathans used to lie out o"
    "n the hillside at night and take long shots into the camp. A bullet ripped through the canvas of"
    " the hospital tent\342\200\224that was all. The surgeon crept out to his own quarters, and his o"
    "rderly discovered him half-an-hour afterward lying in his blood stone-dead.\342\200\235\n\n\342"
    "\200\234Hit?\342\200\235 exclaimed the major.\n\n\342\200\234Not a bit of it,\342\200\235 said t"
    "he surgeon. \342\200\234He had quietly opened his instrument-case in the dark, taken out a lance"
    "t, and severed his femoral artery. Sheer panic, do you see, at the whistle of a bullet.\342\200"
    "\235\n\nEven upon these men, case-hardened to horrors, the incident related in its bald simplici"
    "ty wrought its effect. From some there broke a half-uttered exclamation of disbelief; others mov"
    "ed restlessly in their chairs with a sort of physical discomfort, because a man had sunk so far "
    "below humanity. Here an officer gulped his wine, there a second shook his shoulders as though to"
    " shake the knowledge off as a dog shakes water. There was only one in all that company who sat p"
    "erfectly still in the silence which followed upon the story. That one was the boy, Harry Feversh"
    "am.\n\nHe sat with his hands now clenched upon his knees and leaning forward a little across the"
    " table toward the surgeon, his cheeks white as paper, his eyes burning, and burning with ferocit"
    "y. He had the look of a dangerous animal in the trap. His body was gathered, his muscles taut. S"
    "utch had a fear that the lad meant to leap across the table and strike with all his strength in "
    "the savagery of despair. He had indeed reached out a restraining hand when General Feversham\342"
    "\200\231s matter-of-fact voice intervened, and the boy\342\200\231s attitude suddenly relaxed.\n"
    "\n\342\200\234Queer incomprehensible things happen. Here are two of them. You can only say they "
    "are the truth and pray God you may forget \342\200\231em. But you can\342\200\231t explain, for "
    "you can\342\200\231t understand.\342\200\235\n\nSutch was moved to lay his hand upon Harry\342"
    "\200\231s shoulder.\n\n\342\200\234Can you?\342\200\235 he asked, and regretted the question alm"
    "ost before it was spoken. But it was spoken, and Harry\342\200\231s eyes turned swiftly toward S"
    "utch, and rested upon his face, not, however, with any betrayal of guilt, but quietly, inscrutab"
    "ly. Nor did he answer the question, although it was answered in a fashion by General Feversham."
    "\n\n\342\200\234Harry understand!\342\200\235 exclaimed the general, with a snort of indignation"
    ". \342\200\234How should he? He\342\200\231s a Feversham.\342\200\235\n\nThe question, which Har"
    "ry\342\200\231s glance had mutely put before, Sutch in the same mute way repeated. \342\200\234A"
    "re you blind?\342\200\235 his eyes asked of General Feversham. Never had he heard an untruth so "
    "demonstrably untrue. A mere look at the father and the son proved it so. Harry Feversham wore hi"
    "s father\342\200\231s name, but he had his mother\342\200\231s dark and haunted eyes, his mother"
    "\342\200\231s breadth of forehead, his mother\342\200\231s delicacy of profile, his mother\342"
    "\200\231s imagination. It needed perhaps a stranger to recognise the truth. The father had been "
    "so long familiar with his son\342\200\231s aspect that it had no significance to his mind.\n\n"
    "\342\200\234Look at the clock, Harry.\342\200\235\n\nThe hour\342\200\231s furlough had run out."
    " Harry rose from his chair, and drew a breath.\n\n\342\200\234Good night, sir,\342\200\235 he sa"
    "id, and walked to the door.\n\nThe servants had long since gone to bed; and, as Harry opened the"
    " door, the hall gaped black like the mouth of night. For a second or two the boy hesitated upon "
    "the threshold, and seemed almost to shrink back into the lighted room as though in that dark voi"
    "d peril awaited him. And peril did\342\200\224the peril of his thoughts.\n\nHe stepped out of th"
    "e room and closed the door behind him. The decanter was sent again upon its rounds; there was a "
    "popping of soda-water bottles; the talk revolved again in its accustomed groove. Harry was in an"
    " instant forgotten by all but Sutch. The lieutenant, although he prided himself upon his imparti"
    "al and disinterested study of human nature, was the kindliest of men. He had more kindliness tha"
    "n observation by a great deal. Moreover, there were special reasons which caused him to take an "
    "interest in Harry Feversham. He sat for a little while with the air of a man profoundly disturbe"
    "d. Then, acting upon an impulse, he went to the door, opened it noiselessly, as noiselessly pass"
    "ed out, and, without so much as a click of the latch, closed the door behind him.\n\nAnd this is"
    " what he saw: Harry Feversham, holding in the centre of the hall a lighted candle high above his"
    " head, and looking up toward the portraits of the Fevershams as they mounted the walls and were "
    "lost in the darkness of the roof. A muffled sound of voices came from the other side of the door"
    " panels, but the hall itself was silent. Harry stood remarkably still, and the only thing which "
    "moved at all was the yellow flame of the candle as it flickered apparently in some faint draught"
    ". The light wavered across the portraits, glowing here upon a red coat, glittering there upon a "
    "corselet of steel. For there was not one man\342\200\231s portrait upon the walls which did not "
    "glisten with the colours of a uniform, and there were the portraits of many men. Father and son,"
    " the Fevershams had been soldiers from the very birth of the family. Father and son, in lace col"
    "lars and bucket boots, in Ramillies wigs and steel breastplates, in velvet coats with powder on "
    "their hair, in shakos and swallowtails, in high stocks and frogged coats, they looked down upon "
    "this last Feversham, summoning him to the like service. They were men of one stamp; no distincti"
    "on of uniform could obscure their relationship\342\200\224lean-faced men, hard as iron, rugged i"
    "n feature, thin-lipped, with firm chins and straight, level mouths, narrow foreheads, and the st"
    "eel-blue inexpressive eyes; men of courage and resolution, no doubt, but without subtleties, or "
    "nerves, or that burdensome gift of imagination; sturdy men, a little wanting in delicacy, hardly"
    " conspicuous for intellect; to put it frankly, men rather stupid\342\200\224all of them, in a wo"
    "rd, first-class fighting men, but not one of them a first-class soldier.\n\nBut Harry Feversham "
    "plainly saw none of their defects. To him they were one and all portentous and terrible. He stoo"
    "d before them in the attitude of a criminal before his judges, reading his condemnation in their"
    " cold unchanging eyes. Lieutenant Sutch understood more clearly why the flame of the candle flic"
    "kered. There was no draught in the hall, but the boy\342\200\231s hand shook. And finally, as th"
    "ough he heard the mute voices of his judges delivering sentence and admitted its justice, he act"
    "ually bowed to the portraits on the wall. As he raised his head, he saw Lieutenant Sutch in the "
    "embrasure of the doorway.\n\nHe did not start, he uttered no word; he let his eyes quietly rest "
    "upon Sutch and waited. Of the two it was the man who was embarrassed.\n\n\342\200\234Harry,\342"
    "\200\235 he said, and in spite of his embarrassment he had the tact to use the tone and the lang"
    "uage of one addressing not a boy, but a comrade equal in years, \342\200\234we meet for the firs"
    "t time tonight. But I knew your mother a long time ago. I like to think that I have the right to"
    " call her by that much misused word \342\200\230friend.\342\200\231 Have you anything to tell me"
    "?\342\200\235\n\n\342\200\234Nothing,\342\200\235 said Harry.\n\n\342\200\234The mere telling so"
    "metimes lightens a trouble.\342\200\235\n\n\342\200\234It is kind of you. There is nothing.\342"
    "\200\235\n\nLieutenant Sutch was rather at a loss. The lad\342\200\231s loneliness made a strong"
    " appeal to him. For lonely the boy could not but be, set apart as he was, no less unmistakably i"
    "n mind as in feature, from his father and his father\342\200\231s fathers. Yet what more could h"
    "e do? His tact again came to his aid. He took his card-case from his pocket.\n\n\342\200\234You "
    "will find my address upon this card. Perhaps some day you will give me a few days of your compan"
    "y. I can offer you on my side a day or two\342\200\231s hunting.\342\200\235\n\nA spasm of pain "
    "shook for a fleeting moment the boy\342\200\231s steady inscrutable face. It passed, however, sw"
    "iftly as it had come.\n\n\342\200\234Thank you, sir,\342\200\235 Harry monotonously repeated. "
    "\342\200\234You are very kind.\342\200\235\n\n\342\200\234And if ever you want to talk over a di"
    "fficult question with an older man, I am at your service.\342\200\235\n\nHe spoke purposely in a"
    " formal voice, lest Harry with a boy\342\200\231s sensitiveness should think he laughed. Harry t"
    "ook the card and repeated his thanks. Then he went upstairs to bed.\n\nLieutenant Sutch waited u"
    "ncomfortably in the hall until the light of the candle had diminished and disappeared. Something"
    " was amiss, he was very sure. There were words which he should have spoken to the boy, but he ha"
    "d not known how to set about the task. He returned to the dining room, and with a feeling that h"
    "e was almost repairing his omissions, he filled his glass and called for silence.\n\n\342\200"
    "\234Gentlemen,\342\200\235 he said, \342\200\234this is June 15th,\342\200\235 and there was gre"
    "at applause and much rapping on the table. \342\200\234It is the anniversary of our attack upon "
    "the Redan. It is also Harry Feversham\342\200\231s birthday. For us, our work is done. I ask you"
    " to drink the health of one of the youngsters who are ousting us. His work lies before him. The "
    "traditions of the Feversham family are very well known to us. May Harry Feversham carry them on!"
    " May he add distinction to a distinguished name!\342\200\235\n\nAt once all that company was on "
    "its feet.\n\n\342\200\234Harry Feversham!\342\200\235\n\nThe name was shouted with so hearty a g"
    "oodwill that the glasses on the table rang. \342\200\234Harry Feversham, Harry Feversham,\342"
    "\200\235 the cry was repeated and repeated, while old General Feversham sat in his chair with a "
    "face aflush with pride. And a boy a minute afterward in a room high up in the house heard the mu"
    "ffled words of a chorus\342\200\224\n\nFor he\342\200\231s a jolly good fellow, For he\342\200"
    "\231s a jolly good fellow, For he\342\200\231s a jolly good fellow, And so say all of us,\n\nFor"
    " he\342\200\231s a jolly good fellow, For he\342\200\231s a jolly good fellow, For he\342\200"
    "\231s a jolly good fellow, And so say all of us,\n\nand believed the guests upon this Crimean ni"
    "ght were drinking his father\342\200\231s health. He turned over in his bed and lay shivering. H"
    "e saw in his mind a broken officer slinking at night in the shadows of the London streets. He pu"
    "shed back the flap of a tent and stooped over a man lying stone-dead in his blood, with an open "
    "lancet clinched in his right hand. And he saw that the face of the broken officer and the face o"
    "f the dead surgeon were one\342\200\224and that one face, the face of Harry Feversham.";

#endif
