#ifndef CONTENT_H
#define CONTENT_H

const char chapter_title[] = "CHAPTER II:\nTHE VOID";

const char chapter_content[] =
    "The S3 processor hummed softly as the first line appeared. In this machine, "
    "black is not pigment but silence, because every dark pixel is a diode at rest. "
    "The panel does not glow behind the words. The words themselves are the glow.\n\n"
    "At midnight, the room was quiet enough to hear fingertips crossing glass. "
    "A chapter opened. A sentence settled. Then another. The scroll felt less "
    "like movement and more like gravity, as if language itself were falling "
    "through a narrow column of light.\n\n"
    "The display controller accepted each transfer at speed, not as a flourish "
    "but as discipline. Data arrived in ordered bursts. Lines appeared with no "
    "hesitation. The eye does not care about bus transactions or DMA descriptors, "
    "yet it notices instantly when rhythm is broken.\n\n"
    "That is why pre-rendering matters. The expensive decisions happen once: "
    "glyph shape, kerning, spacing, and baseline. During scrolling, the system "
    "does not negotiate style. It does not ask how a letter should look. It only "
    "moves already-decided pixels into view.\n\n"
    "A good reader pipeline respects two clocks. The first is human: how quickly "
    "the hand changes direction and how abruptly attention shifts. The second is "
    "electrical: how long a full frame transfer takes on a shared bus. Stability "
    "comes from treating both clocks as real constraints, never assumptions.\n\n"
    "In early prototypes, long paragraphs looked beautiful until memory collapsed "
    "under ambition. One giant bitmap solved simplicity but failed scale. The next "
    "design split the page into segments, each segment complete on its own, each "
    "segment replaceable without disturbing what stayed on screen.\n\n"
    "A segment is not a paragraph and not a sentence. It is a bounded region in "
    "pixel space, chosen for cache behavior. A segment may hold part of a paragraph, "
    "yet line boundaries remain intact because layout is indexed before rendering. "
    "Words do not fracture. Letters do not shear.\n\n"
    "The touch controller reports position in quick intervals, and the render task "
    "translates difference into scroll offset. If the offset has not changed enough, "
    "nothing is sent. If it has, the nearest prepared segment is blitted. In this "
    "way idle time stays cold while interaction remains warm.\n\n"
    "Readers notice this as confidence. There is no shimmer at paragraph edges and "
    "no nervous jump when the thumb pauses. The text tracks intent instead of racing "
    "ahead. Even in dense passages, the page feels anchored, as if every sentence "
    "already knew where it belonged.\n\n"
    "Storage follows a similar rule. Keep source text compact and immutable. Keep "
    "layout metadata small and cheap to rebuild. Keep rendered segments ephemeral, "
    "because they are only a speed layer. Persistence should remember content and "
    "position, not every intermediate pixel.\n\n"
    "When chapters become long, indexing quality matters more than brute memory. "
    "A robust index maps byte ranges to logical lines and logical lines to y offsets. "
    "With that map, the renderer can request exactly the lines needed for a segment "
    "without scanning the whole chapter each time.\n\n"
    "Hyphenation policy also becomes visible at scale. Some books prefer strict word "
    "preservation and wider ragged edges. Others allow soft hyphens for cleaner shapes. "
    "Either choice can be deterministic if the tokenizer and line-break algorithm "
    "operate on code point boundaries, not raw bytes.\n\n"
    "Consider multilingual text. A single visual character may use multiple bytes and "
    "sometimes multiple code points. Splitting blindly by byte count can cut through a "
    "character and produce invalid UTF-8. Splitting by grapheme cluster avoids this and "
    "keeps cursor, selection, and line wrapping coherent.\n\n"
    "In practice, performance and readability are not enemies. The cache can prioritize "
    "what is near the viewport while a background task prepares what is likely next. "
    "Fast downward motion biases future segments below. Reverse motion rebalances above. "
    "The policy is simple, but the effect feels intelligent.\n\n"
    "The system audit running every few seconds tells the truth no animation can hide. "
    "If frame rate drops under load, prefetch depth is too shallow or segment height is "
    "poorly chosen. If CPU rises at idle, redraw gating is too permissive. Metrics turn "
    "guessing into engineering.\n\n"
    "There is a practical art to choosing segment height. Too short and metadata overhead "
    "dominates. Too tall and cache misses become expensive. The best value depends on bus "
    "throughput, touch cadence, and the average speed of a human thumb on this device.\n\n"
    "An e-reader is successful when the hardware disappears. You should not feel SPI lanes, "
    "task priorities, or memory regions. You should feel cadence and comprehension. The "
    "software earns that invisibility by preparing work before the eye asks for it.\n\n"
    "By dawn, the chapter was still open, red on black, steady and quiet. The device had "
    "become what it was meant to be: not a benchmark in your hand, but a page that never "
    "fights the reader. In the dark, that is enough.\n\n"
    "Appendix: Segment stress text begins here to increase payload length for testing. "
    "Paragraph A repeats structural patterns of long prose with varied punctuation, "
    "numbers like 240x536, and references to buses, caches, and tasks. Paragraph B "
    "extends line count further so that render windows cross many boundaries in one drag. "
    "Paragraph C introduces short lines, long lines, and abrupt sentence endings. Stop. "
    "Continue. Resume. Drift. Accelerate. Decelerate. Hold. Release. Repeat.\n\n"
    "Appendix continued: The quick brown fox does not jump here; it scrolls. It scrolls "
    "through diagnostics, through timing windows, through memory pressure, through long "
    "conversation and quiet pauses. It scrolls until the segment cache proves itself under "
    "realistic chapter length, then it scrolls farther, because confidence is built at the "
    "edges where ordinary demos usually stop.";

#endif